// Code generated by "stringer -type=RollingKind -trimprefix=RollingKind"; DO NOT EDIT.

package logx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RollingKindNone-1]
	_ = x[RollingKindDaily-2]
	_ = x[RollingKindHourly-3]
	_ = x[RollingKindMinutely-4]
	_ = x[RollingKindSize-5]
	_ = x[_RollingKindMax-6]
}

const _RollingKind_name = "NoneDailyHourlyMinutelySize_RollingKindMax"

var _RollingKind_index = [...]uint8{0, 4, 9, 15, 23, 27, 42}

func (i RollingKind) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_RollingKind_index)-1 {
		return "RollingKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RollingKind_name[_RollingKind_index[idx]:_RollingKind_index[idx+1]]
}
