package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"github.com/suruiran/cube"
	"github.com/suruiran/cube/ccli"
)

var (
	defaultignores = []string{
		"**/node_modules/*",
		"**/.git/*",
		"**/.DS_Store",
		"**/__pycache__/*",
		"**/internal/*",
		"**/vendor/*",
		"**/.idea/*",
		"**/.vscode/*",
		"**/*_test.go",
	}
)

func main() {
	var (
		scanrootflag = flag.String("root", "", "root directory")
		ignores      ccli.Items[string]
		outflag      = flag.String("o", "", "output file")
		ismainflag   = flag.Bool("m", true, "is main package, default is true")
	)
	flag.Var(&ignores, "i", "ignore patterns")
	flag.Parse()

	ignores.Items = append(ignores.Items, defaultignores...)

	if *scanrootflag == "" {
		fmt.Println("empty scan root directory, -root")
		flag.Usage()
		return
	}

	if *outflag == "" {
		fmt.Println("empty output file, -o")
		flag.Usage()
		return
	}

	gomodc, err := os.ReadFile("./go.mod")
	if err != nil {
		panic(err)
	}
	modname := ""
	for line := range strings.SplitSeq(string(gomodc), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				modname = parts[1]
			}
			break
		}
	}
	if len(modname) >= 2 && modname[0] == '"' && modname[len(modname)-1] == '"' {
		modname = modname[1 : len(modname)-1]
	}

	seq, err := cube.FsScanStream(context.Background(), *scanrootflag, &cube.WalkOptions{
		MatchPatterns:  []string{"*.go"},
		IgnorePatterns: ignores.Items,
		MaxDepth:       10,
	})

	if err != nil {
		panic(err)
	}

	var dirs = make(cube.Set[string])
	for item, err := range seq {
		if err != nil {
			continue
		}
		dirs.Add(item.Dir)
	}

	lines := []string{}
	head := ""

	if *ismainflag {
		head = "package main\n"
	} else {
		head = fmt.Sprintf("package %s\n", filepath.Base(modname))
	}

	pkgroot, _ := filepath.Abs(".")
	scanroot, _ := filepath.Abs(*scanrootflag)
	prefix, _ := filepath.Rel(pkgroot, scanroot)
	if prefix == "." {
		prefix = ""
	}

	for dir := range dirs {
		dir, _ = filepath.Abs(dir)
		remain := filepath.ToSlash(dir[len(scanroot):])
		if remain == "" {
			continue
		}
		if prefix != "" {
			remain = fmt.Sprintf("/%s%s", prefix, remain)
		}
		lines = append(lines, fmt.Sprintf(`    _ "%s%s"`, modname, remain))
	}
	slices.Sort(lines)
	lines = append([]string{
		fmt.Sprintf("// Code generated by cube/x/tools/autoimport @ %s; DO NOT EDIT.", time.Now().Format(time.RFC3339)),
		head,
		"import ("},
		lines...,
	)
	lines = append(lines, ")")

	err = os.WriteFile(*outflag, []byte(strings.Join(lines, "\n")), 0600)
	if err != nil {
		panic(err)
	}
}
