package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"github.com/suruiran/cube"
	"github.com/suruiran/cube/ccli"
)

var (
	defaultignores = []string{
		"**/node_modules/*",
		"**/.git/*",
		"**/.DS_Store",
		"**/__pycache__/*",
		"**/internal/*",
	}
)

func main() {
	var (
		scanrootflag = flag.String("root", "", "root directory")
		ignores      ccli.Strings
		outflag      = flag.String("o", "", "output file")
		ismainflag   = flag.Bool("m", true, "is main package, default is true")
	)
	flag.Var(&ignores, "i", "ignore patterns")
	flag.Parse()

	ignores = append(ignores, defaultignores...)

	if *scanrootflag == "" || *outflag == "" {
		flag.Usage()
		return
	}

	gomodc, err := os.ReadFile("./go.mod")
	if err != nil {
		panic(err)
	}
	modname := ""
	for line := range strings.SplitSeq(string(gomodc), "\n") {
		if strings.HasPrefix(line, "module") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				modname = parts[1]
			}
			break
		}
	}

	seq, err := cube.FsWalkStream(*scanrootflag, &cube.WalkOptions{
		MatchPatterns:  []string{"*.go"},
		IgnorePatterns: []string(ignores),
		MaxDepth:       10,
	})

	if err != nil {
		panic(err)
	}

	var dirs = make(cube.Set[string])
	for item, err := range seq {
		if err != nil {
			panic(err)
		}
		if filepath.Base(item.Dir) == "internal" {
			continue
		}
		dirs.Add(item.Dir)
	}

	lines := []string{}
	head := ""

	if *ismainflag {
		head = "package main\n"
	} else {
		lidx := strings.LastIndex(modname, "/")
		if lidx == -1 {
			lidx = 0
		}
		head = fmt.Sprintf("package %s\n", modname[lidx+1:])
	}

	pkgroot, _ := filepath.Abs(".")
	scanroot, _ := filepath.Abs(*scanrootflag)
	prefix, _ := filepath.Rel(pkgroot, scanroot)
	if prefix == "." {
		prefix = ""
	}

	for dir := range dirs {
		dir, _ = filepath.Abs(dir)
		remain := filepath.ToSlash(dir[len(scanroot):])
		if remain == "" {
			continue
		}
		if prefix != "" {
			remain = fmt.Sprintf("/%s%s", prefix, remain)
		}
		lines = append(lines, fmt.Sprintf(`    _ "%s%s"`, modname, remain))
	}
	slices.Sort(lines)
	lines = append([]string{
		fmt.Sprintf("// Code generated by cube/x/tools/autoimport @ %s; DO NOT EDIT.", time.Now().Format(time.RFC3339)),
		head,
		"import ("},
		lines...,
	)
	lines = append(lines, ")")

	err = os.WriteFile(*outflag, []byte(strings.Join(lines, "\n")), 0o644)
	if err != nil {
		panic(err)
	}
}
